### ISSUE TITLE
Use existing glauth environment?

### ISSUE THREAD

**Issue by surfrock66** [sonicnkt/glauth-ui#13]
I have an existing glauth environment that I would like to manage with glauth-ui.  It's using just the config file.  I don't quite understand from the README but it seems that when you set this up, you create a blank glauth environment then this exports a .cfg which can be used.  Is it possible to import from an existing glauth environment?

**Comment by traverseda** [comment]
Right now all the user information, stuff like passwords or usernames, need to exist in glauth-ui's database. There's no support for importing from an existing glauth config file.

How big is your config file? If it's only a dozen users you could do something like this by hand by reading through the config file and using something like this [sqlite gui](https://sqlitebrowser.org/) to create database entries that match your glauth config. Everything accept the password can be set via glauth-ui, for the password you'd need to take the password from the config and put it directly into the database, otherwise the UI would try to hash the password again.

**Comment by sonicnkt** [comment]
like @traverseda said, there is no working import yet. 
I have this on my road map and even some basic import code available (not public yet since broken in parts, especially groups) but since not all glauth user options (SSH Keys, 2FA, Home Folder, etc) are implemented yet this wouldnt work for all setups anyway.

If you dont need more than the currently implemented user options i could maybe implement a working import function but this would take some days since im quite busy atm on my day job.

**Comment by surfrock66** [comment]
I think my understanding was that glauthui would work with existing glauth, and the missing attributes could be managed in a config file.  For example, I could create users and manage passwords in the ui, then edit the cfg file for the home directory and other attributes.  If that's not the case, I'll probably have to hold off until glauth-ui is a little more full featured as I do need to manage those posix attributes and they're already defined in my cfg file.

**Comment by sonicnkt** [comment]
at the moment it rewrites the whole conifg file from scratch as this was the easiest method and i wouldnt have to write a special parser that replaces only certain lines etc.
There is some unmerged code for glauth that support dbs as backend and this would make the method you described a lot easier to implement but as it wasnt officially available i wrote the ui as it is today. 

If you could supply a more advanced config file (with any imporant/secure info removed) it would help me to see what may be needed for more advanced setups. Like i wrote in the README, i have no use for those (yet) as i am mainly using this for services where im only checking for names and groupmembership.
